# Makefile.subdirs
# Wolfgang Tichy 1/2019, Bernd Bruegmann 5/02
# The commands in here are used in all standard source subdirectories.
# For example, in the coordinates directory there is a Makefile containing the
# lines:
#
# NAME := coordinates
# OBJS := nmesh_$(NAME).o get_coords.o
# include $(TOP)/Makefile.subdirs

# We work in a separate directory LIBDIR to not clutter the source
# directories with object files and library files.

# Make name of the library that we want to create
NEWLIB := lib$(NAME).a

# directory for the library
LIBDIR  = $(TOP)/lib

# directory for the object files of this library
OBJDIR  = $(LIBDIR)/obj/$(NAME)
OBJSWITHPATH = $(addprefix $(OBJDIR)/,$(OBJS))

# CCFLAGS has CFLAGS plus any other flags we want to add here
CCFLAGS = $(CFLAGS)
CCFLAGS += -DMODULEREV="$$(git rev-parse --short HEAD)"


# main target: build library from object files. AR has these options:
# d: delete files
# r: replace files
# u: update only those files for which a newer version is given
# c: create archive without warning
# s: symbol table is created (ar s = ranlib), needed for interdependencies
# note that $@ is the matched target
$(LIBDIR)/$(NEWLIB): $(OBJSWITHPATH)
	$(AR) rcs $@ $(OBJSWITHPATH)


# secondary target: build object files
# note that $@ is the matched target, $* is the stem of the target defined by %
# we use:
$(OBJDIR)/%.o: %.c $(TOP)/src/main/main/nmesh.h nmesh_$(NAME).h $(NAME).h Makefile
	$(CC) $(CCFLAGS)  -o $@  -c $*.c

# same, but build if it is a C++ file
$(OBJDIR)/%.o: %.cpp $(TOP)/src/main/main/nmesh.h nmesh_$(NAME).h $(NAME).h Makefile
	$(CXX) $(CCFLAGS)  -o $@  -c $*.cpp

## First try for C and C++:
## [ Note: $(wildcard %.c*) should be the same as %.c*, but is not ]
#$(OBJDIR)/%.o: %.c* $(TOP)/src/main/main/nmesh.h nmesh_$(NAME).h $(NAME).h Makefile
#	@if [ -f $*.cpp ]; \
#	then echo $(CXX) $(CFLAGS) -o $@ -c $*.cpp ; \
#	          $(CXX) $(CFLAGS) -o $@ -c $*.cpp ; \
#	else echo $(CC) $(CFLAGS) -o $@ -c $*.c  ; \
#	          $(CC) $(CFLAGS) -o $@ -c $*.c  ; \
#	fi;
