# output/Makefile

NAME := basis

OBJS := nmesh_$(NAME).o $(NAME).o Legendre.o Lagrange.o gridpoints.o \
	SphericalHarmonics.o filter.o SpinWeightedSphericalHarmonics.o \
	interpolate.o Fourier.o

include $(TOP)/Makefile.subdirs
