# ADMconstraints.py
# Wolfgang Tichy 11/2021

# compute ADM constraints from ADM variables


########################################################################
# Initilize code generator:
########################################################################
# get file SymPyToC.py directly into here (like when we include in C)
codegen = '../../Math/SymPyToC/SymPyToC.py'
exec(compile(open(codegen).read(), codegen, 'exec'))


########################################################################
# indices we need, and their min and max value in brackets
########################################################################
a = sympy.Idx('a', (1, 3))
b = sympy.Idx('b', (1, 3))
c = sympy.Idx('c', (1, 3))
d = sympy.Idx('d', (1, 3))
e = sympy.Idx('e', (1, 3))
#f = sympy.Idx('f', (1, 3))

# define some functions that we only use in C
#fabs = sympy.symbols('fabs', cls=sympy.Function)
#Cal  = sympy.symbols('Cal', cls=sympy.Function)
fabs = sympy.Function('fabs')
Cal  = sympy.Function('Cal')


########################################################################
# Program Text and Eqations (in one long string list)
########################################################################
tocompute = (
  ':Text = #include \"nmesh.h\"\n',
  ':Text = #include \"ADM.h\"\n',
  ':Text = \n',
  ':Text = #define POWER(x,y) (pow((double) (x), (double) (y)))\n',
  ':Text = #define Log(x)     log((double) (x)))\n',
  ':Text = #define POW2(x)    ((x)*(x))\n',
  ':Text = #define POW2inv(x) (1.0/((x)*(x)))\n',
  ':Text = #define POW1inv(x) (1.0/(x))\n',
  ':Text = #define Cal(x,y,z) ((x)?(y):(z))\n\n',

  ':Text = \n\n\n',

  ':Text = void ADMconstraints(tVarList *u)\n',
  ':Text = {\n',
  ':Text = tMesh *mesh = u->mesh;\n',
  ':Text = \n',

  ':Text = int normConstr = Getv(Par(\"ADM_normalizedConstraints\"), \"yes\");\n',
  ':Text = int TermByTerm = GetvLax(Par(\"ADM_ConstraintNorm\"), \"TermByTerm\");\n',
  ':Text = \n',
  ':Text = int iADM_gxx     = Ind(\"ADM_gxx\");\n',
  ':Text = int iADM_dgxxx   = Ind(\"ADM_dgxxx\");\n',
  ':Text = int iADM_ddgxxxx = Ind(\"ADM_ddgxxxx\");\n',
  ':Text = int iADM_alpha   = Ind(\"ADM_alpha\");\n',
  ':Text = int iADM_dalphax   = Ind(\"ADM_dalphax\");\n',
  ':Text = int iADM_ddalphaxx = Ind(\"ADM_ddalphaxx\");\n',
  ':Text = int iADM_Kxx     = Ind(\"ADM_Kxx\");\n',
  ':Text = int iADM_dKxxx   = Ind(\"ADM_dKxxx\");\n',
  ':Text = \n',

  ':Text = formylnodes(mesh)\n',
  ':Text = {\n',
  ':Text = tNode *node = MyLnode;\n',
  ':Text = int ijk;\n\n',
''':Text =
  cart_partials_dSij_dk_dSij_dkl(node, iADM_gxx, iADM_dgxxx, iADM_ddgxxxx);
  cart_partials_dU_di_dU_dij(node, iADM_alpha, iADM_dalphax, iADM_ddalphaxx);
  cart_partials_dSij_dk(node, iADM_Kxx, iADM_dKxxx);
''',
  ':Text = \n',

  ':Text = forpoints(node, ijk)\n',
  ':Text = {\n',

# custom variable declaration
# we have to translate between the tensor names and the C variables
# we may need special variables, for example for parameters

#prdecvl[{g[a,b], K[a,b], alpha, beta[a], rho, j[a], S[a,b],
#         ham, mom[a], trK, dtrKdt, normham, normmom[a]}, "u"];
''':Decl: g[a,b]; K[a,b]; alpha; beta[a]; rho; j[a]; S[a,b];
          ham; mom[a]; trK; dtrKdt; normham; normmom[a]; :
          Access={VAR}{COMP}[ijk] : Format =
  double *{VAR}{COMP} = Vard( node, Vind(u,{LI}) );
''',
#prdecvarname[{dg[a,b,c]},    "ADM_dgxxx"];
#prdecvarname[{ddg[a,b,c,d]}, "ADM_ddgxxxx"];
#prdecvarname[{dK[a,b,c]},    "ADM_dKxxx"];
#prdecvarname[{dalpha[a]},    "ADM_dalphax"];
#prdecvarname[{ddalpha[a,b]}, "ADM_ddalphaxx"];
''':Decl: dg[a,b,c]; dK[a,b,c]; :
          Access={VAR}{COMP}[ijk] : Format =
  double *{VAR}{COMP} = Vard( node, Vind(vlu, Ind("ADM_{VAR}xxx")+{CI} );
''',
''':Decl: ddg[a,b,c,d]; :
          Access={VAR}{COMP}[ijk] : Format =
  double *{VAR}{COMP} = Vard( node, Vind(vlu, Ind("ADM_{VAR}xxxx")+{CI} );
''',
''':Decl: dalpha[a]; :
          Access={VAR}{COMP}[ijk] : Format =
  double *{VAR}{COMP} = Vard( node, Vind(vlu, Ind("ADM_{VAR}x")+{CI} );
''',
''':Decl: ddalpha[a,b] :
          Access={VAR}{COMP}[ijk] : Format =
  double *{VAR}{COMP} = Vard( node, Vind(vlu, Ind("ADM_{VAR}xx")+{CI} );
''',
# auxillary variables are automatically generated by this
''':Decl: AUTOVARS :
          Access={VAR}{COMP} : Format =
  double {VAR}{COMP}; // ID={VARID} comp={CI} listpos={LI}
''',
# variables we use but are not declared in C, e.g. macros
''':Decl: PI
''',

  # partial derivatives
  'delg[c,a,b] = dg[a,b, c]',         # OD[g[a,b], c]    # del[c,g[a,b]]
  'deldelg[a,b,c,d] = ddg[c,d, a,b]', # OD2[g[c,d], a,b] # deldel[a,b,g[c,d]]
  'delK[a,b,c] = dK[b,c, a]',         # OD[K[b,c], a]    #  del[a, K[b,c]]

  # inverse physical metric
  'ginvdet[a,b] = matrixinvdet(g[a,b])',
  'detg = ginvdet[1,c]*g[1,c]',
  'ginv[a,b] = ginvdet[a,b] / detg',

  # connection of physical metric
  'gammado[c,a,b] = 1/2*(delg[a,b,c] + delg[b,a,c] - delg[c,a,b])',
  'gamma[c,a,b] = ginv[c,d]*gammado[d,a,b]',

  # curvature of physical metric
  'gamgam[a,b, c,d] = gamma[e,a,b]*gammado[e,c,d]',
  #'R[a,b] = ginv[c,d]*( 1/2*(\
  #  - deldelg[c,d,a,b] - deldelg[a,b,c,d] + \
  #    deldelg[a,c,b,d] + deldelg[b,c,a,d]) +\
  #    gamma[e,a,c]*gammado[e,b,d] - \
  #    gamma[e,a,b]*gammado[e,c,d])',
  'R[a,b] = ginv[c,d]*( 1/2*(\
    - deldelg[c,d,a,b] - deldelg[a,b,c,d] + \
      deldelg[a,c,b,d] + deldelg[b,c,a,d]) +\
    + gamgam[a,c,b,d] - gamgam[a,b,c,d])',
  'R = ginv[a,b]*R[a,b]',

  # extrinsic curvature terms
  'Kud[a,b] = ginv[a,c]*K[c,b]',
  'K = Kud[a,b]*Kdelta[a,b]',
  'KudKud = Kud[a,b]*Kud[b,a]',
  'codelK[a,b,c] = delK[a,b,c] - gamma[d,a,b]*K[d,c] - gamma[d,a,c]*K[b,d]',
  'cdKudd[a,b,c] = ginv[a,d]*codelK[d,b,c]',

  # use matter terms, but only if the vars are enabled
  ":Text = if(rho==NULL) {",
    'hamrhs = 0',
  ":Text = } else {",
    'hamrhs = 16*PI*rho',
  ":Text = }",

  ":Text = if(j1==NULL) {",
    'momrhs[a] = 0',
  ":Text = } else {",
    'momrhs[a] = 8*PI*j[a]',
  ":Text = }",

  # Hamiltonian constraint
  'ham = R + K*K - KudKud - hamrhs',

  # momentum constraint
  'momu[a] = ginv[a,b]*cdKudd[c,b,d]*Kdelta[c,d] - ginv[b,c]*cdKudd[a,b,c]',
  'mom[a] = g[a,b]*momu[b] - momrhs[a]',

  # trace of extrinsic curvature
  'trK = K',

  # time derivative of trace of extrinsic curvature
  # derivatives of the lapse
  'cdda[a,b] = ddalpha[a,b] - gamma[c,a,b]*dalpha[c]',
  'trcdda = ginv[a,b]*cdda[a,b]',
  'dtrK[a] = ginv[b,c]*codelK[a,b,c]',
  'betadtrK = beta[a]*dtrK[a]',
  ":Text = if(S11==NULL) {",
    'Sminus3rho = 0',
  ":Text = } else {",
    'Sminus3rho = ginv[a,b]*S[a,b] - 3*rho',
  ":Text = }",
  'dtrKdt = -trcdda + alpha*(R + K*K) + betadtrK + alpha * 4*PI*Sminus3rho',

  # compute normalized constraints
  ':Text = if(normConstr) {',

    # normalized Hamiltonian constraint
    # normham = ham/(fabs(R) + K K + fabs(Kud[a,b] Kud[b,a]) + fabs(hamrhs)),
    ':Text = if(TermByTerm) {\n',
      # compute fabs of some terms in R separately
      'RA[a,b] = ginv[c,d] * (-deldelg[c,d,a,b])',
      'RB[a,b] = ginv[c,d] * ( deldelg[a,c,b,d])',
      'RC[a,b] = ginv[c,d] * ( gamgam[a,c,b,d])',
      'RD[a,b] = ginv[c,d] * (-gamgam[a,b,c,d])',
      'RA = ginv[a,b]*RA[a,b]',
      'RB = ginv[a,b]*RB[a,b]',
      'RC = ginv[a,b]*RC[a,b]',
      'RD = ginv[a,b]*RD[a,b]',
      # hamnum = RA + RB + RC + RD + K*K - KudKud - hamrhs,
      'denom  = fabs(RA)+fabs(RB)+fabs(RC)+fabs(RD) + K*K + fabs(KudKud) +\
                fabs(hamrhs)',
    ':Text = } else {\n',
      'denom  = fabs(R) + K*K + fabs(KudKud) + fabs(hamrhs)',
    ':Text = }',

    'normham = Cal(denom <= 0.0, 0.0, ham/denom)',

    # normalized momentum constraint
    # 'normmom[a] = mom[a]/( fabs( cdKudd[c,a,d]*Kdelta[c,d] ) \
    #                         +fabs( ginv[b,c]*codelK[a,b,c] ) )',
    ':Text = if(TermByTerm) {\n',
      # compute fabs of some terms in codelK separately
      'codelKA[a,b,c] =  delK[a,b,c]',
      'codelKB[a,b,c] = -gamma[d,a,b]*K[d,c]',
      'codelKC[a,b,c] = -gamma[d,a,c]*K[b,d]',
      'cdKdA[b] = ginv[a,c]*codelKA[a,b,c]',
      'cdKdB[b] = ginv[a,c]*codelKB[a,b,c]',
      'cdKdC[b] = ginv[a,c]*codelKC[a,b,c]',
      'codelTrKA[a] = ginv[b,c]*codelKA[a,b,c]',
      'codelTrKB[a] = ginv[b,c]*codelKB[a,b,c]',
      'codelTrKC[a] = ginv[b,c]*codelKC[a,b,c]',
      # note: mom[la] =  CD[ K[la,ue], le ] - CD[ TrK, la ]
      # 'momnum[a] = cdKdA[a] + cdKdB[a] + cdKdC[a] -\
      #                codelTrKA[a] - codelTrKB[a] - codelTrKC[a] -momrhs[a]',
      'denom[a] =  fabs(cdKdA[a]) + fabs(cdKdB[a]) + fabs(cdKdC[a]) +\
                   fabs(codelTrKA[a]) + fabs(codelTrKB[a]) +\
                   fabs(codelTrKC[a]) + fabs(momrhs[a])',
    ':Text = } else {\n',
      'denom[a]  = fabs(cdKudd[c,a,d]*Kdelta[c,d]) + \
                   fabs(ginv[b,c]*codelK[a,b,c]) + fabs(momrhs[a])',
    ':Text = }\n',

    ':Text ='
    'denom = denom1 + denom2 + denom3;',

    'normmom[a] = Cal(denom <= 0.0, 0.0, mom[a]/denom)',

  ':Text = }\n',

# the end or tail of the function (we need at least a })
  ':Text = } /* end of points */\n',
  ':Text = } /* end of nodes */\n',
  ':Text = \n\n',
  ':Text = }  /* end of function */\n\n',
)

if __name__ == '__main__':
  ########################################################################
  # Create pool of processes. Can use multiprocessing or multiprocess
  ########################################################################
  import multiprocessing as mp
  #mp.set_start_method('fork')
  #mp.set_start_method('spawn')
  #mp.set_start_method('forkserver')
  #import multiprocess as mp
  mp_pool = mp.Pool()
  SymPyToC_pool = mp_pool

  ########################################################################
  # get all Eqn components and the undeclared vars that only appear on LHS
  ########################################################################
  Eqs = read_LHS_RHS_strlist(tocompute)
  allEqs, AUTOVARS = assemble_all_EqnComponents(Eqs)

  ########################################################################
  # declare all symmetries for all variables we use
  ########################################################################
  symmetries = {
  g[a,b] :        { '+': ( [b,a], ) },
  K[a,b] :        { '+': ( [b,a], ) },
  R[a,b] :        { '+': ( [b,a], ) },
  ginv[a,b] :     { '+': ( [b,a], ) },
  #ddpop[a,b] :    { '+': ( [b,a], ) },
  S[a,b] :        { '+': ( [b,a], ) },

  delg[c,a,b] :   { '+': ( [c,b,a], ) },
  delK[c,a,b] :   { '+': ( [c,b,a], ) },
  deldelg[a,b,c,d] :  { '+': ( [b,a,c,d], [a,b,d,c], ) },
  ddalpha[a,b] :      { '+': ( [b,a], ) },

  gamma[c,a,b] :   { '+': ( [c,b,a], ) },
  gammado[c,a,b] : { '+': ( [c,b,a], ) },
  #(* hidden symmetries for contraction! careful, not general *)
  #   gamma/: gamma[a_, b_, c_] gammado[a_, d_, e_] :=
  #   gammado[a, b, c] gamma[a, d, e] /; !OrderedQ[{{b,c},{d,e}}]
  # INSTEAD we use the var:
  #'gamgam[a,b,c,d] = gamma[e,a,b]*gammado[e,c,d]',
  gamgam[a,b,c,d] : { '+': ( [b,a,c,d], [a,b,d,c], [c,d,a,b], ) },

  codelK[c,a,b] :  { '+': ( [c,b,a], ) },
  cdKudd[c,a,b] :  { '+': ( [c,b,a], ) },

  RA[a,b] :        { '+': ( [b,a], ) },
  RB[a,b] :        { '+': ( [b,a], ) },
  RC[a,b] :        { '+': ( [b,a], ) },
  RD[a,b] :        { '+': ( [b,a], ) },
  codelKA[c,a,b] : { '+': ( [c,b,a], ) },
  codelKB[c,a,b] : { '+': ( [c,b,a], ) },
  codelKC[c,a,b] : { '+': ( [c,b,a], ) },
  #cdKuddA[c,a,b] : { '+': ( [c,b,a], ) },
  #cdKuddB[c,a,b] : { '+': ( [c,b,a], ) },
  #cdKuddC[c,a,b] : { '+': ( [c,b,a], ) },

  #OD2[c,a,b] :     { '+': ( [c,b,a], ) },

  dg[a,b,c] :      { '+': ( [b,a,c], ) },
  dK[a,b,c] :      { '+': ( [b,a,c], ) },

  ddg[a,b,c,d] :   { '+': ( [b,a,c,d], [a,b,d,c], ) },
  }


  ########################################################################
  # apply symmetries and remove duplicates. This step takes the longest.
  ########################################################################
  allEqs = apply_symmetries_to_all_EqnComponents(symmetries, Eqs, allEqs, AUTOVARS)

  ########################################################################
  # run user defined simplifications on RHSs (this is optional)
  ########################################################################
  SymPyToC_pool = None # switch off paralellization pool, because of pickle...
  collect_ginv = lambda expr : expr.collect([ginv[1,1],ginv[1,2],ginv[1,3],
                                             ginv[2,2],ginv[2,3],ginv[3,3]])
  allEqs = simplify_all_EqnComponents(collect_ginv, allEqs)
  SymPyToC_pool = mp_pool # reset pool

  ########################################################################
  # run more sympy simplification operations on RHSs (this is optional)
  ########################################################################
  #allEqs = simplify_all_EqnComponents(sympy.simplify, allEqs)
  #allEqs = simplify_all_EqnComponents(sympy.expand, allEqs)
  allEqs = simplify_all_EqnComponents(sympy.N, allEqs)

  ########################################################################
  # now write all into a .c file
  ########################################################################
  cfilename = __file__.replace('.py', '.c')
  write_Eqs(cfilename, allEqs, AUTOVARS)

  ########################################################################
  # close pool of processes
  ########################################################################
  if SymPyToC_pool != None:
    SymPyToC_pool.close()
