/* main.c */
/* Wolfgang Tichy, Jan. 2019 */

#include "nmesh.h"
#include "main.h"
#include <time.h> // for time and ctime functions

/* global vars */
nMPI_Comm main_comm;  /* MPI communicator made at start of main */
tMesh *main_mesh;     /*contains the mesh made in main */


/* initialize libraries: calls the initializers for each module,
   nmesh_automatic_initialize.c is autogenerated by Makefile */
void initialize_libraries(struct tMESH *mesh)
{
  prdivider(1);
  printf("Initializing libraries\n");
#include "nmesh_automatic_initialize.c"
}

/**************************************************************************/
/* main */
int main(int argc, char **argv) 
{
  tMesh *mesh;
  
  nMPI_Init(&argc, &argv);
  wait_for_debugger_if_NMESH_MPI_DEBUG();
  nMPI_Comm_dup(nMPI_COMM_WORLD, &(main_comm));

  /* set time when nmesh was started */
  initTimeIn_s();

  /* make first mesh in which we store pars, vars and funs */
  mesh = make_empty_mesh(0);
  main_mesh = mesh; /* save this mesh in a global var as well */

  /* start the main parts of nmesh: */
  read_command_line(mesh, argc, argv);
  parse_parameter_file(mesh, Gets(Par("parameterfile")));
  parse_command_line_options(mesh);
  make_output_directory(mesh);
  initialize_libraries(mesh);
  TIMER_START;

  /* print skeleton of function bins */
  PrintMeshFuncs(mesh);

  /* hook for funs to run 1st */
  RunFun(FIRST);

  iterate_parameters(mesh, 0); /* start of new iteration */
  while(iterate_parameters(mesh, 1))
  {
    inidata_mesh(mesh);
    evolve_mesh(mesh);
    free_mesh_patches_and_nodes(mesh);

    /* set a par so we can find output from previous par iteration */
    makeparameter(mesh, "outdir_previous_iteration", "",
                  "outdir of previous iteration");
    Sets(Par("outdir_previous_iteration"), Gets(Par("outdir")));
  }

  TIMER_STOP;
  finalize_mesh(mesh);
  prTimeIn_s("WallTime after main's call to finalize_mesh: ");
  free(mesh);
  nMPI_Comm_free(&(main_comm));
  nMPI_Finalize();
  return 0;
}


/* read command line */
int read_command_line(tMesh *mesh, int argc, char **argv)
{
  int i; 

  if(0) 
    for(i = 0; i < argc; i++) printf("argv[%d] = %s\n", i, argv[i]);

  if(Rank0)
  {
    prdivider(1);
    printf("Welcome to nmesh (rev " MSTR_OFVAL(MAINREV)
           "), compiled on %s at %s\n", __DATE__, __TIME__);
    prdivider(1);
  }

  if(argc < 2)
  {
    if(Rank0)
    {
      printf("Usage:  nmesh name.par\n");
      printf("or:     nmesh name.par options and extra arguments\n");
      printf("\n");
      printf("options: --keep_previous          do not touch name_previous\n");
      printf("         --modify-par:\"P=v\"       set par P to value v\n");
      printf(" all options must start with --\n");
    }
    finalize_all_and_exit(mesh, 0);
  }

  /* this par is needed here already, so that finalexit can check it */
  if(Rank0) printf("Making first parameters\n");
  makeparameter(mesh, "errorexit", "exit", "how we exit");
  /* this is about how we output */
  makeparameter(mesh, "logfile_creation", "yes", "whether we create logfile");

  /* got two or more arguments? */
  if (argc >= 2)
  {
    int nopts, nargs;
    char argi[1000];
    char descr[1000];
    char options[1000];
    char *parfile = (char *) calloc(strlen(argv[1])+40, sizeof(char));
    char *outdir  = (char *) calloc(strlen(argv[1])+40, sizeof(char));
    int parnamelen;

    /* determine name of parameter file and output directory */
    strcpy(parfile, argv[1]);
    parnamelen = strlen(parfile);
    if(!strstr(parfile, ".par") || parnamelen<5) strcat(parfile, ".par");
    parnamelen = strlen(parfile);
    if(!strstr(parfile+parnamelen-4, ".par")) strcat(parfile, ".par");
    strcpy(outdir, parfile);
    outdir[strlen(outdir)-4]=0; /* remove .par */

    /* first parameter initializes parameter data base */
    if(Rank0) printf("Adding command line parameters\n");
    makeparameter(mesh, "outdir", outdir, "output directory");
    makeparameter(mesh, "parameterfile", parfile, 
                  "name of parameter file given on command line");

    /* add other args */
    nargs=nopts=0;
    options[0]=0;
    for(i=2; i<argc; i++)
    {
      if(argv[i][0]=='-')
      {
        if(strlen(argv[i])==1) errorexit("- is not a valid option");
        if(argv[i][1]!='-') errorexit("all options must start with --");
        /* save all options in options */
        if(nopts>0) strncat(options, " ", 999);
        strncat(options, argv[i], 999);
        nopts++;
      }
      else
      {
        snprintf(argi, 999, "nmesh_arg%d", nargs+2);
        snprintf(descr, 999, "nmesh command line argument%d", nargs+2);
        makeparameter(mesh, argi, argv[i], descr);
        if(Rank0) printf("  %s = %s\n", argi, Gets(Par(argi)));
        nargs++;
      }
    }
    /* add nmesh command line options */
    if(nopts>0)
    {
      makeparameter(mesh, "nmesh_options", options,
                    "nmesh command line options");
      if(Rank0)
        printf("  nmesh_options = %s\n", Gets(Par("nmesh_options")));
    }
    free(parfile);
    free(outdir);
  }

  /* more initialization */
  
  return 0;
}


int make_output_directory(tMesh *mesh)
{
  char *outdir  = Gets(Par("outdir"));
  char *outdirp = (char *) calloc(strlen(outdir)+40, sizeof(char));
  time_t mytime = time(NULL);       // get time
  char *time_str = ctime(&mytime);
  int keep_previous = GetvLax(ParLax("nmesh_options"), "--keep_previous");
  int chkpt = checkpoint_exists(mesh, "", "");
  int move_old;

  /* check if a shell is available to execute commands later */
  /* NOTE: system2 and system3 are smart enough to do "mkdir", "rm -rf"
           and "mv" even without a shell by using POSIX calls. */
  if(system(NULL)==0 && Rank0)
  {
    printf("WARNING: system(NULL)=0 => cannot execute shell commands!\n");
    printf("         Consider using system_emu.\n");
  }

  /* set outdirp to outdir_previous */
  strcpy(outdirp, outdir);
  strcat(outdirp, "_previous");

  /* check if we remove outdir_previous and then mv outdir to outdir_previous */
  move_old = (!keep_previous) && (!chkpt);
  if(move_old)
  {
    /* check if we have a checkpoint in outdir+"_previous" */
    if(checkpoint_exists(mesh, "_previous", ""))
    {
      printf("*** Refusing to delete %s ***\n", outdirp);
      errorexits("There is a checkpoint in %s_previous", outdir);
    }

    /* remove outdir_previous and move outdir to outdir_previous */
    if(Rank0)
    {
      system2("rm -rf", outdirp);
      system3("mv", outdir, outdirp);
    }
  }

  /* make output directory, save parfile */
  if(Rank0)
  {
    system2("mkdir", outdir);
    copy_file_into_dir(Gets(Par("parameterfile")), outdir);
  }
  /* all wait here until mkdir and copy are done. */
  nMPI_barrier();

  /* redirect stdout */
  redirect_stdout_and_stderr(mesh, "a");

  /* say what we have after redirection: */
  prdivider(1);
  time_str[strlen(time_str)-1] = '\0';
  printf("The current time is %s.\n", time_str);
  printf("nmesh (rev " MSTR_OFVAL(MAINREV)
         ") compiled on %s at %s:", __DATE__, __TIME__);
  printf("  MAX_NTHREADS = %d\n", MAX_NTHREADS);
  printf("  outdir = %s\n", outdir);

  free(outdirp);
  return 0;
}


/* go through options and act accordingly */
int parse_command_line_options(tMesh *mesh)
{
  char *optionstr;
  char *str1;
  char *str2;
  char *par;
  char *val;

  //PRF;printf(":\nPar(\"nmesh_options\")=%i\n", Par("nmesh_options"));
  /* get length of nmesh_options string */
  if(GetsLax(ParLax("nmesh_options"))==0) return 0;
  if(Rank0) printf("Parsing command line options\n");

  /* parse for all --modify-par: */
  optionstr = strdup((GetsLax(ParLax("nmesh_options"))));
  str1 = optionstr;
  while( (str1=strstr(str1, "--modify-par:"))!=NULL )
  {
    str1+=13;
    str2=strstr(str1, "=");
    if(str2==NULL) break;
    str2[0]=0; /* replace = with 0 */
    par=str1;
    val=str2+1;
    str2=strstr(val, " --");
    if(str2!=NULL) str2[0]=0; /* now val is 0 terminated for sure */
    if(0) printf("par=%s|val=%s|\n", par,val);
    
    /* set par to new value */
    AddOrModifyPar(par, val, "set with --modify-par option");

    /* move forward in str1 */
    if(str2!=NULL) str2[0]=' '; /* restore space before -- */
    str1=val;
    if(0) printf("str1=%s|\n", str1);
  }
  free(optionstr);
  return 0;
} 

/* redirect stdout */
int redirect_stdout_and_stderr(tMesh *mesh, const char *mode)
{
  char *outdir  = Gets(Par("outdir"));
  char f[100];
  char so[1000];

  /* filename format for stdout files */
  snprintf(f,99, "%%s/stdout.%%0%dd", (int) log10(nMPI_size())+1);

  /* redirect stdout and stderr for rank0 */
  if(Rank0 && !Getv(Par("logfile_creation"),"no"))
  {
    //snprintf(so,999, "%s.log", outdir);
    snprintf(so,999, f, outdir, 0);
    prdivider(3);
    printf("*** NOTE ***  Output from proc0 redirected to:\n %s\n", so);
    prdivider(3);
    freopen(so, mode, stdout);
    freopen(so, mode, stderr);
  }

  /* rank0 announces that others will be redirected as well */
  if(Rank0 && nMPI_size()>1)
  {
    snprintf(so,999, f, outdir, 1);
    prdivider(3);
    printf("*** NOTE ***  Output from other procs redirected to e.g.:\n %s\n",
           so);
    prdivider(3);
  }

  /* redirect stdout and stderr. Do it for all MPI ranks>0
     all output is collected in e.g. outdir/stdout.001 ... */
  if(nMPI_rank()>0)
  {
    snprintf(so,999, f, outdir, nMPI_rank());
    freopen(so, mode, stdout);
    freopen(so, mode, stderr);
  }

  return 0;
}

/* delete current output and move _previous back */
int move_previous_output_to_outdir(tMesh *mesh)
{
  char *outdir  = Gets(Par("outdir"));
  char *outdirp = (char *) calloc(strlen(outdir)+40, sizeof(char));

  /* set outdirp to outdir_previous */
  strcpy(outdirp, outdir);
  strcat(outdirp, "_previous");

  /* all wait here, until all has been written before moving dirs */
  fflush(stdout);
  fflush(stderr);
  nMPI_barrier();

  if(Rank0)
  {
    /* delete outdir and move previous back to outdir */
    system2("rm -rf", outdir);
    system3("mv", outdirp, outdir);
  }

  /* all wait here until move is done. */
  nMPI_barrier();
  /* NOTE: this may not work!!!
     on koko system3("mv", outdirp, outdir) was finished on node0, but node1
     still saw the old outdir! So redirection below went to the wrong dir! */

  /* redirect output again */
  redirect_stdout_and_stderr(mesh, "a");

  free(outdirp);
  return 0;
}


/* get initial data for mesh */
int inidata_mesh(tMesh *mesh)
{
  int chkpt;

  prdivider(0);
  printf("Initializing mesh\n");
  prTimeIn_s("WallTime at beginning of inidata_mesh: ");

  /* hook for funs right after iterate_parameters */
  RunFun(POST_PARAMETERS);

  /* check if there is a saved checkpoint, and if we want checkpointing */
  chkpt = Getb(Par("checkpoint")) && checkpoint_exists(mesh, "", "");

  /* load stage 0 of checkpoint if it exists */
  if(chkpt)
  {
    prdivider(1);
    printf("Restarting from checkpoint:\n");
    checkpoint_load_stage(mesh, "", 0);
  }
  else /* intialize mesh if there is no checkpoint */
  {
    /* create a mesh */
    amr_setup_mesh(mesh);

    /* here we schedule funcs to programatically set up the mesh */
    RunFun(INITMESH);
  }

  /* no matter if there is a saved checkpoint or not, we initialize
     everything now (we may even recompute initial data) */

  /* move nodes to differnt procs */
  RunFun(LOADBALANCING);

  /* setup coords */
  RunFun(PRE_COORDINATES);
  RunFun(COORDINATES);
  RunFun(POST_COORDINATES);

  /* compute initial data */
  RunFun(PRE_INITIALDATA);
  RunFun(INITIALDATA);
  RunFun(POST_INITIALDATA);

  /* initial data is just another new time slice */
  RunFun(POST_EVOLVE);

  /* initial data complete */
  prdivider(0);
  printf("Done with initialization\n");
  printf(" iteration %d, time=%g\n", mesh->iteration, mesh->time);

  /* load next stage of checkpoint, or save checkpoint */
  if(chkpt)
  {
    checkpoint_load_stage(mesh, "", 1);
    //write_mesh(mesh, -1, -2);
    //exit(9);
  }
  else
  {
    checkpoint_save_if_needed(mesh, 1);
  }

  /* analyze initial data or data from checkpoint */
  RunFun(ANALYZE);

  /* output for permanent variables */
  RunFun(OUTPUT);

  /* post output */
  RunFun(POST_OUTPUT);

  return 0;
}


/* evolve mesh */
int evolve_mesh(tMesh *mesh)
{
  int iterationmax = Geti(Par("iterations"));
  double timemax   = Getd(Par("finaltime"));

  prdivider(0);
  prTimeIn_s("WallTime at beginning of evolve_mesh: ");

  if(timemax > 0)
    iterationmax = timemax/mesh->dt + 0.5;

  if(iterationmax > 0) 
    printf("Evolving mesh until iteration %d at time %g\n",
	   iterationmax, iterationmax * mesh->dt);

  if(iterationmax <= 0) return 0;

  /* outermost evolution loop */
  while(mesh->iteration < iterationmax)
  { 
    /* pre evolve */
    RunFun(PRE_EVOLVE); 

    /* make one evolution step */
    RunFun(EVOLVE); 

    /* post evolve */
    RunFun(POST_EVOLVE); 

    /* the evolution step is complete now */
    mesh->iteration++;
    mesh->time = mesh->iteration * mesh->dt;

    /* print some info */
    printf(" iteration %d, time=%g\n", mesh->iteration, mesh->time);
    fflush(stdout); 

    /* call analyze functions */
    RunFun(ANALYZE);

    /* save checkpoint */
    checkpoint_save_if_needed(mesh, 0);

    /* call output functions, say for variable output */
    RunFun(OUTPUT);

    /* post output */
    RunFun(POST_OUTPUT);

    /* AMR and load balancing */
    RunFun(AMR);
    RunFun(LOADBALANCING);
    //RunFun(REINIT);
  
    /* update since this may change during evolution, say when checkpointing */
    timemax = Getd(Par("finaltime"));
    iterationmax
      = (timemax > 0) ? timemax/mesh->dt + 0.5 : Geti(Par("iterations"));
  }

  /* write checkpoint at the end */
  checkpoint_save_if_needed(mesh, 1);
  prTimeIn_s("WallTime at end of evolve_mesh: ");

  return 0;
}



/* finalize mesh */
int finalize_mesh(tMesh *mesh)
{
  RunFun(FINALIZEMESH);
  free_mesh_contents(mesh);
  if(0) prTimeIn_s("WallTime at end of finalize_mesh: ");
  return 0;
}


/* finalize all and the exit with code ec */
void finalize_all_and_exit(tMesh *mesh, int ec)
{
  finalize_mesh(mesh);
  free(mesh);
  nMPI_Comm_free(&(main_comm));
  nMPI_Finalize();
  fflush(stderr);
  fflush(stdout);
  exit(ec);
}
