/* main.c */
/* Wolfgang Tichy, Jan. 2019 */

#include "nmesh.h"
#include "main.h"
#include <time.h>    /* for time and ctime functions */
#include <unistd.h>  /* for sync */

/* global vars */
nMPI_Comm main_comm;  /* MPI communicator made at start of main */
tMesh *main_mesh;     /* contains the mesh made in main */
const char *compiledphysics; /* set in nmesh_automatic_initialize.c */
int main_ncalls;             /* number of calls to main */
int NMESH_memory_persists;   /* if 1 do not free in finalize_all */


/* initialize libraries: calls the initializers for each module,
   nmesh_automatic_initialize.c is autogenerated by Makefile */
void initialize_libraries(struct tMESH *mesh)
{
  prdivider(1);
  printf("Initializing libraries\n");
#include "nmesh_automatic_initialize.c"
}

/**************************************************************************/
/* main */
int main(int argc, char **argv) 
{
  tMesh *mesh;

  main_ncalls++;

  /* init some stuff only once */
  if(main_ncalls <= 1)
  {
    /* init MPI */
    nMPI_Init(&argc, &argv);
    wait_for_debugger_if_NMESH_MPI_DEBUG();
    nMPI_Comm_dup(nMPI_COMM_WORLD, &(main_comm));

    /* set time when nmesh was started */
    initTimeIn_s();
  }

  /* make first mesh in which we store pars, vars and funs */
  mesh = make_empty_mesh(0);
  main_mesh = mesh; /* save this mesh in a global var as well */

  /* start the main parts of nmesh: */
  read_command_line(mesh, argc, argv);
  parse_parameter_file(mesh, Gets(Par("parameterfile")));
  parse_command_line_options(mesh);
  make_output_directory(mesh);
  RunFun(PRE_INITLIBS);  /* for funcs to run before initialize_libraries */
  main_mesh = mesh;      /* in case a func in PRE_INITLIBS has called main */
  enable_FPEEXCEPTIONS();
  print_system_info();
  initialize_libraries(mesh);
  TIMER_START;

  /* print skeleton of function bins */
  PrintMeshFuncs(mesh);

  /* hook for funcs to run just after initialize_libraries */
  RunFun(POST_INITLIBS);

  iterate_parameters(mesh, 0); /* start of new iteration */
  while(iterate_parameters(mesh, 1))
  {
    inidata_mesh(mesh);
    evolve_mesh(mesh);
    RunFun(FINALIZE); /* hook for funcs to run after each par iteration */
    free_mesh_patches_and_nodes(mesh);

    /* set a par so we can find output from previous par iteration */
    makeparameter(mesh, "outdir_previous_iteration", "",
                  "outdir of previous iteration");
    Sets(Par("outdir_previous_iteration"), Gets(Par("outdir")));
  }

  TIMER_STOP;
  prTimeIn_s("WallTime just before main's call to finalize_all: ");
  finalize_all(mesh);
  PRF;printf(": nmesh has finished.\n");
  main_ncalls--;
  return 0;
}


/* read command line */
int read_command_line(tMesh *mesh, int argc, char **argv)
{
  int i; 

  if(0) 
    for(i = 0; i < argc; i++) printf("argv[%d] = %s\n", i, argv[i]);

  if(Rank0)
  {
    prdivider(1);
    printf("Welcome to nmesh (rev " MSTR_OFVAL(MAINREV)
           "), compiled on %s at %s\n", __DATE__, __TIME__);
    prdivider(1);
  }

  if(argc < 2)
  {
    if(Rank0)
    {
      printf("Usage:  nmesh name.par\n");
      printf("or:     nmesh name.par options and extra arguments\n");
      printf("\n");
      printf("options: --keep_previous          do not touch name_previous\n");
      printf("         --modify-par:\"P=v\"       set par P to value v\n");
      printf(" all options must start with --\n");
    }
    finalize_all_and_exit(mesh, 0);
  }

  /* this par is needed here already, so that finalexit can check it */
  if(Rank0) printf("Making first parameters\n");
  makeparameter(mesh, "errorexit", "exit", "how we exit");
  /* this is about how we output */
  makeparameter(mesh, "logfile_creation", "yes", "whether we create logfile");

  /* got two or more arguments? */
  if (argc >= 2)
  {
    int nopts, nargs;
    char argi[1000];
    char descr[1000];
    char options[1000];
    char *parfile = (char *) calloc(strlen(argv[1])+40, sizeof(char));
    char *outdir  = (char *) calloc(strlen(argv[1])+40, sizeof(char));
    int parnamelen;

    /* determine name of parameter file and output directory */
    strcpy(parfile, argv[1]);
    parnamelen = strlen(parfile);
    if(!strstr(parfile, ".par") || parnamelen<5) strcat(parfile, ".par");
    parnamelen = strlen(parfile);
    if(!strstr(parfile+parnamelen-4, ".par")) strcat(parfile, ".par");
    strcpy(outdir, parfile);
    outdir[strlen(outdir)-4]=0; /* remove .par */

    /* first parameter initializes parameter data base */
    if(Rank0) printf("Adding command line parameters\n");
    makeparameter(mesh, "outdir", outdir, "output directory");
    makeparameter(mesh, "parameterfile", parfile, 
                  "name of parameter file given on command line");

    /* add other args */
    nargs=nopts=0;
    options[0]=0;
    for(i=2; i<argc; i++)
    {
      if(argv[i][0]=='-')
      {
        if(strlen(argv[i])==1) errorexit("- is not a valid option");
        if(argv[i][1]!='-') errorexit("all options must start with --");
        /* save all options in options */
        if(nopts>0) strncat(options, " ", 999);
        strncat(options, argv[i], 999);
        nopts++;
      }
      else
      {
        snprintf(argi, 999, "nmesh_arg%d", nargs+2);
        snprintf(descr, 999, "nmesh command line argument%d", nargs+2);
        makeparameter(mesh, argi, argv[i], descr);
        if(Rank0) printf("  %s = %s\n", argi, Gets(Par(argi)));
        nargs++;
      }
    }
    /* add nmesh command line options */
    if(nopts>0)
    {
      makeparameter(mesh, "nmesh_options", options,
                    "nmesh command line options");
      if(Rank0)
        printf("  nmesh_options = %s\n", Gets(Par("nmesh_options")));
    }
    free(parfile);
    free(outdir);
  }

  /* more initialization */
  
  return 0;
}


int make_output_directory(tMesh *mesh)
{
  char *outdir  = Gets(Par("outdir"));
  char *outdirp = (char *) calloc(strlen(outdir)+40, sizeof(char));
  time_t mytime = time(NULL);       // get time
  char *time_str = ctime(&mytime);
  int keep_previous = GetvLax(ParLax("nmesh_options"), "--keep_previous");
  int chkpt = checkpoint_exists(mesh, "", "");
  int move_old;

  /* check if a shell is available to execute commands later */
  /* NOTE: system2 and system3 are smart enough to do "mkdir", "rm -rf"
           and "mv" even without a shell by using POSIX calls. */
  if(system(NULL)==0 && Rank0)
  {
    printf("WARNING: system(NULL)=0 => cannot execute shell commands!\n");
    printf("         Consider using system_emu.\n");
  }

  /* set outdirp to outdir_previous */
  strcpy(outdirp, outdir);
  strcat(outdirp, "_previous");

  /* check if we remove outdir_previous and then mv outdir to outdir_previous */
  move_old = (!keep_previous) && (!chkpt);
  if(move_old)
  {
    /* check if we have a checkpoint in outdir+"_previous" */
    if(checkpoint_exists(mesh, "_previous", ""))
    {
      printf("*** Refusing to delete %s ***\n", outdirp);
      errorexits("There is a checkpoint in %s_previous", outdir);
    }

    /* remove outdir_previous and move outdir to outdir_previous */
    if(Rank0)
    {
      system2("rm -rf", outdirp);
      system3("mv", outdir, outdirp);
    }
  }

  /* make output directory, save parfile */
  if(Rank0)
  {
    system2("mkdir", outdir);
    copy_file_into_dir(Gets(Par("parameterfile")), outdir);
  }
  /* all wait here until mkdir and copy are done. */
  nMPI_barrier();

  /* redirect stdout */
  redirect_stdout_and_stderr(mesh, "a");

  /* say what we have after redirection: */
  prdivider(1);
  time_str[strlen(time_str)-1] = '\0';
  if(!GetvLax(ParLax("logfile_reproducible"),"yes"))
  {
    printf("The current time is %s.\n", time_str);
    printf("nmesh (rev " MSTR_OFVAL(MAINREV)
           ") compiled on %s at %s:", __DATE__, __TIME__);
    printf("  MAX_NTHREADS = %d\n", MAX_NTHREADS);
  }
  printf("  outdir = %s\n", outdir);

  free(outdirp);
  return 0;
}


/* go through options and act accordingly */
int parse_command_line_options(tMesh *mesh)
{
  char *optionstr;
  char *str1;
  char *str2;
  char *par;
  char *val;

  //PRF;printf(":\nPar(\"nmesh_options\")=%i\n", Par("nmesh_options"));
  /* get length of nmesh_options string */
  if(GetsLax(ParLax("nmesh_options"))==0) return 0;
  if(Rank0) printf("Parsing command line options\n");

  /* parse for all --modify-par: */
  optionstr = strdup((GetsLax(ParLax("nmesh_options"))));
  str1 = optionstr;
  while( (str1=strstr(str1, "--modify-par:"))!=NULL )
  {
    str1+=13;
    str2=strstr(str1, "=");
    if(str2==NULL) break;
    str2[0]=0; /* replace = with 0 */
    par=str1;
    val=str2+1;
    str2=strstr(val, " --");
    if(str2!=NULL) str2[0]=0; /* now val is 0 terminated for sure */
    if(0) printf("par=%s|val=%s|\n", par,val);
    
    /* set par to new value */
    AddOrModifyPar(par, val, "set with --modify-par option");

    /* move forward in str1 */
    if(str2!=NULL) str2[0]=' '; /* restore space before -- */
    str1=val;
    if(0) printf("str1=%s|\n", str1);
  }
  free(optionstr);
  return 0;
} 

/* redirect stdout */
int redirect_stdout_and_stderr(tMesh *mesh, const char *mode)
{
  char *outdir  = Gets(Par("outdir"));
  char f[100];
  char so[1000];

  /* filename format for stdout files */
  snprintf(f,99, "%%s/stdout.%%0%dd", (int) log10(nMPI_size())+1);
  if(Getv(Par("logfile_creation"),"/dev/null")) snprintf(f,99, "/dev/null");

  /* redirect stdout and stderr for rank0 */
  if(Rank0 && Getv(Par("logfile_creation"),"yes"))
  {
    //snprintf(so,999, "%s.log", outdir);
    snprintf(so,999, f, outdir, 0);
    prdivider(3);
    printf("*** NOTE ***  Output from proc0 redirected to:\n %s\n", so);
    prdivider(3);
    freopen(so, mode, stdout);
    freopen(so, mode, stderr);
  }

  /* rank0 announces that others will be redirected as well */
  if(Rank0 && nMPI_size()>1 && !Getv(Par("logfile_creation"),"none"))
  {
    snprintf(so,999, f, outdir, 1);
    prdivider(3);
    printf("*** NOTE ***  Output from other procs redirected to e.g.:\n %s\n",
           so);
    prdivider(3);
  }

  /* redirect stdout and stderr. Do it for all MPI ranks>0
     all output is collected in e.g. outdir/stdout.001 ... */
  if(nMPI_rank()>0 && !Getv(Par("logfile_creation"),"none"))
  {
    snprintf(so,999, f, outdir, nMPI_rank());
    freopen(so, mode, stdout);
    freopen(so, mode, stderr);
  }

  return 0;
}

/* delete current output and move _previous back */
int move_previous_output_to_outdir(tMesh *mesh)
{
  char *outdir  = Gets(Par("outdir"));
  char *outdirp = (char *) calloc(strlen(outdir)+40, sizeof(char));

  /* set outdirp to outdir_previous */
  strcpy(outdirp, outdir);
  strcat(outdirp, "_previous");

  /* all wait here, until all has been written before moving dirs */
  fflush(stdout);
  fflush(stderr);
  nMPI_barrier();

  if(Rank0)
  {
    /* delete outdir and move previous back to outdir */
    system2("rm -rf", outdir);
    system3("mv", outdirp, outdir);
  }

  /* all wait here until move is done. */
  nMPI_barrier();
  /* NOTE: this may not work!!!
     on koko system3("mv", outdirp, outdir) was finished on node0, but node1
     still saw the old outdir! So redirection below went to the wrong dir! */

  /* redirect output again */
  redirect_stdout_and_stderr(mesh, "a");

  free(outdirp);
  return 0;
}

/* Open a file where we use a buffer with a size read from pars
   fread_bufsize or fwrite_bufsize. The buffer buf is allocated here and
   needs to be freed later, e.g. by calling fclose_buf. */
FILE *fopen_bufsize(tMesh *mesh, const char *pathname, const char *mode,
                    char **buf)
{
  if(mode[0] == 'r')
    return fopen_buf(pathname, mode, buf, Geti(Par("fread_bufsize")));
  else
    return fopen_buf(pathname, mode, buf, Geti(Par("fwrite_bufsize")));
}

/* commit filesystem caches to disk if desired */
int fs_sync(tMesh *mesh)
{
  int fs_sync = Par("fs_sync");

  if(Getb(fs_sync)) sync();

  return 0;
}

/* check if all in par physics has actually been compiled in */
int check_compiledphysics(tMesh *mesh)
{
  char *physics = Gets(Par("physics"));
  char *phys, *str, *sav;

  if(!Getb(Par("logfile_reproducible")))
    printf("compiledphysics = %s\n", compiledphysics);
  printf("physics = %s\n", physics);

  /* loop over all in par physics and check if each is in compiledphysics */
  phys = strdup(physics);
  for(str=strtok_r(phys, " ", &sav); str!=NULL;
      str=strtok_r(NULL, " ", &sav))
  {
    if(!strstr(compiledphysics, str))
      errorexits("%s has not been compiled, "
                 "but is included in the parameter physics.\n"
                 "Hint: check your MyConfig and parameter file!", str);
  }
  free(phys);
  return 0;
}


/* get initial data for mesh */
int inidata_mesh(tMesh *mesh)
{
  int checkpoint = Par("checkpoint");
  int chkpt_exists, chkpt0, chkpt1;

  prdivider(0);
  printf("Initializing mesh\n");
  prTimeIn_s("WallTime at beginning of inidata_mesh: ");

  /* hook for funs right after iterate_parameters */
  RunFun(POST_PARAMETERS);

  /* check if there is a saved checkpoint, and if we want checkpointing */
  chkpt_exists = checkpoint_exists(mesh, "", "");
  chkpt0 = (Getb(checkpoint) || Getv(checkpoint, "load_mesh")) && chkpt_exists;
  chkpt1 = Getb(checkpoint) && (chkpt_exists & CHECKPOINT_VARS);

  /* load stage 0 of checkpoint if it exists */
  if(chkpt0)
  {
    prdivider(1);
    printf("Restarting from checkpoint:\n");
    checkpoint_load_stage(mesh, "", 0);
  }
  else /* intialize mesh if there is no checkpoint */
  {
    /* create a mesh */
    amr_setup_mesh(mesh);

    /* here we run scheduled funcs that programatically set up the mesh */
    RunFun(INITMESH);
    RunFun(POST_INITMESH);
  }

  /* no matter if there is a saved checkpoint or not, we initialize
     everything now (we may even recompute initial data) */

  /* move nodes to differnt procs */
  RunFun(LOADBALANCING);

  /* setup coords */
  RunFun(PRE_COORDINATES);
  RunFun(COORDINATES);
  RunFun(POST_COORDINATES);

  /* compute initial data */
  RunFun(PRE_INITIALDATA);
  RunFun(INITIALDATA);
  RunFun(POST_INITIALDATA);

  /* initial data complete */
  prdivider(0);
  printf("Done with initialization\n");
  printf(" iteration %d, time=%g\n", mesh->iteration, mesh->time);

  /* load next stage of checkpoint, or save checkpoint */
  if(chkpt1)
  {
    /* load an unfiltered checkpoint */
    checkpoint_load_stage(mesh, "", 1);
    RunFun(POST_CHECKPOINT_LOAD); /* do things right after loading */
    /* Run the things that are after checkpoint_save_if_needed
       in evolve_mesh, that are not already called after this block. */
    RunFun(FILTER);
  }
  else
  {
    checkpoint_save_if_needed(mesh, 1);
  }

  /* initial data is just another new time slice */
  RunFun(POST_EVOLVE);

  /* analyze initial data or data from checkpoint */
  RunFun(ANALYZE);

  /* output for permanent variables */
  RunFun(OUTPUT);

  /* post output */
  RunFun(POST_OUTPUT);

  return 0;
}


/* evolve mesh */
int evolve_mesh(tMesh *mesh)
{
  int iterationmax = Geti(Par("iterations"));
  double timemax   = Getd(Par("finaltime"));
  double ttol = max2(mesh->dt*1e-7, timemax*1e-14); //tolerance for time comp
  long double Te, te;     /* time = Te + te */
  int Te_evry = 1000000;  /* we let Te -> Te + te  every Te_evry */

  prdivider(0);
  prTimeIn_s("WallTime at beginning of evolve_mesh: ");

  if(timemax <= 0. && iterationmax > 0)
  {
    timemax = iterationmax * mesh->dt;
    printf("Evolving mesh until iteration %d at time %g\n",
           iterationmax, timemax);
  }
  if(timemax <= 0.) return 0;

  //printf("iterationmax=%d timemax=%g\n", iterationmax, timemax);

  /* print skeleton of function bins again, now with evo funcs */
  PrintMeshFuncs(mesh);

  /* outermost evolution loop */
  Te = mesh->time;
  te = 0.;
  while(mesh->time < timemax - ttol)
  {
    /* pre evolve */
    RunFun(PRE_EVOLVE);

    /* make one evolution step */
    RunFun(EVOLVE);

    /* the evolution step is complete now */
    mesh->iteration++;
    /* accumulate time in te until it is time to increase Te */
    te += mesh->dt;
    if(mesh->iteration % Te_evry == 0)
    {
      Te += te; // adding only a larger accumulated te is better if
      te = 0.;  // mesh->time >> mesh->dt
    }
    mesh->time = Te + te; /* best estimate for actual time */

    /* save an unfiltered checkpoint,
       save for sure if time is beyond timemax */
    checkpoint_save_if_needed(mesh, mesh->time >= timemax - ttol);

    /* apply filters after the full evolution step */
    RunFun(FILTER);

    /* post evolve */
    RunFun(POST_EVOLVE);

    /* print some info */
    //printf(" Te=%Lg te=%Lg  ", Te, te);
    printf(" iteration %d, time=%g\n", mesh->iteration, mesh->time);
    fflush(stdout);

    /* call analyze functions */
    RunFun(ANALYZE);

    /* call output functions, say for variable output */
    RunFun(OUTPUT);

    /* post output */
    RunFun(POST_OUTPUT);

    /* AMR and load balancing */
    RunFun(LOADBALANCING);
    RunFun(AMR);
    //RunFun(REINIT);

    /* update since this may change during evolution */
    timemax      = Getd(Par("finaltime"));
    iterationmax = Geti(Par("iterations"));
    if(timemax<=0. && iterationmax>0) timemax = iterationmax * mesh->dt;
  }

  prTimeIn_s("WallTime at end of evolve_mesh: ");

  return 0;
}



/* finalize mesh */
int finalize_mesh(tMesh *mesh)
{
  /* run funcs in last func bin (they may still need the mesh) */
  RunFun(FINALIZEMESH);

  /* get rid of most things except for func skelton an then run last bin */
  free_mesh_contents_exceptMeshFuns(mesh);
  RunFun(POST_FINALIZEMESH);

  /* now remove func skeleton, and erase mesh contents */
  remove_all_MeshFuns(mesh);
  memset(mesh, 0, sizeof(mesh[0]));

  if(0) prTimeIn_s("WallTime at end of finalize_mesh: ");
  return 0;
}

/* free mesh and finalize MPI */
void finalize_all(tMesh *mesh)
{
  if(!NMESH_memory_persists)
  {
    finalize_mesh(mesh);
    free(mesh);
  }
  if(main_ncalls <= 1)
  {
    nMPI_Comm_free(&(main_comm));
    nMPI_Finalize();
  }
}

/* first run all funcs in FINALIZE, then finalize all else */
void RunFunFINALIZE_finalize_all(tMesh *mesh)
{
  if(!NMESH_memory_persists)
    RunFun(FINALIZE); /* hook for funcs to run for a clean return */
  prTimeIn_s("WallTime just before finalize_all: ");
  finalize_all(mesh);
}

/* finalize all and then exit with code ec */
void finalize_all_and_exit(tMesh *mesh, int ec)
{
  NMESH_memory_persists = 0; /* free mem for clean exit */
  main_ncalls = 1;           /* call MPI_Finalize for clean exit */
  finalize_all(mesh);
  PRF;printf(": nmesh is exiting now.\n");
  fflush(stderr);
  fflush(stdout);
  exit(ec);
}

/* first run all funcs in FINALIZE, then exit cleanly */
void RunFunFINALIZE_finalize_all_and_exit(tMesh *mesh, int ec)
{
  RunFun(FINALIZE); /* hook for funcs to run for a clean return */
  prTimeIn_s("WallTime just before finalize_all_and_exit: ");
  finalize_all_and_exit(mesh, ec);
}
