# MemoryMan/Makefile

NAME := amr

OBJS := nmesh_amr.o mesh.o storage.o print.o array.o amr.o \
	surface.o load.o bfaces.o indicators.o refine.o ghostzones.o \
	timing.o test_mesh.o connections.o

include $(TOP)/Makefile.subdirs
