# output/Makefile

NAME := coordinates

OBJS := nmesh_$(NAME).o $(NAME).o get_coords.o derivs.o utilities.o \
	coordtrans_CubedSphere.o ComplexFunctions.o setup_CubedSpheres.o \
	FSurf_CubedSpheres.o


include $(TOP)/Makefile.subdirs
